baseurl = "https://shirokuro331.netlify.com/"
languageCode = "ja"
title = "blog | shirokuro331"
theme = "Hucore"
copyright = "&copy; 2017 shirokuro331| Follow on <a href=\"https://twitter.com/shirokuro331\" target=\"_blank\">Twitter</a>"
googleAnalytics = "UA-106570266-1"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Toshiaki Sasaki"
sharingicons = true
displayauthor = true